# Generated by Django 3.2.22 on 2023-10-11 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0002_alter_asignaciontarea_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontarea',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
